globals:
    $: true
    jquery: true
env:
    browser: true
    amd: true
    jquery: true

rules:
    no-undef: 0
    strict: 0
    global-strict: 0
    no-unused-vars: 1
    no-console: 0
    no-trailing-spaces: 0
    final-newline: 0
